[package]
name = "star_range"
version = "0.1.0"
authors = ["Kusi Musah Hussein <kusimusah@gmail.com>"]
edition = "2018"
repository = "https://github.com/mkhstar/star_range"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
